### ISSUE TITLE
Report Generation - Template

### ISSUE THREAD

**Issue by thornytree** [StetsonMathCS/gitrekt#4]
The Report Generation Team (A^3) will be using Wt (https://www.webtoolkit.eu/wt/). A^3 must become familiar with Wt and use it to develop a template (https://www.webtoolkit.eu/wt/doc/reference/html/classWt_1_1WTemplate.html) for the report generation. Due: Monday April 11, 2016. @atompkin @MrAjsTech

**Comment by atompkin** [comment]
we also can use the google visualization resource, link is below.

: https://developers.google.com/chart/interactive/docs/gallery/piechart#overview
